// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/AToken.rs"]
pub mod AToken;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/ERC20.rs"]
pub mod ERC20;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/IncentivesController.rs"]
pub mod IncentivesController;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/LendingPool.rs"]
pub mod LendingPool;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/LendingPoolConfigurator.rs"]
pub mod LendingPoolConfigurator;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/StableDebtToken.rs"]
pub mod StableDebtToken;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/VariableDebtToken.rs"]
pub mod VariableDebtToken;
