// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/access_controlled_aggregator.rs"]
pub mod access_controlled_aggregator;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/erc20.rs"]
pub mod erc20;
