// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/chainlink_aggregator.rs"]
pub mod chainlink_aggregator;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/erc20.rs"]
pub mod erc20;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/factory.rs"]
pub mod factory;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/pair.rs"]
pub mod pair;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/price_feed.rs"]
pub mod price_feed;
