// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[path = "../target/abi/erc20.rs"]
pub mod erc20;

#[rustfmt::skip]
#[path = "../target/abi/factory.rs"]
pub mod factory;

#[rustfmt::skip]
#[path = "../target/abi/pair.rs"]
pub mod pair;
