// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/controller.rs"]
pub mod controller;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/registrar.rs"]
pub mod registrar;
