// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/chainlink_feed_registry.rs"]
pub mod chainlink_feed_registry;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/curve_calculations.rs"]
pub mod curve_calculations;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/erc20.rs"]
pub mod erc20;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/sushiswap_calculations.rs"]
pub mod sushiswap_calculations;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "../target/abi/yearn_lens_oracle.rs"]
pub mod yearn_lens_oracle;
