[package]
name = "derive_macros"
version = "0.1.18"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.60"
syn = { version = "2.0.18", features = ["full", "extra-traits"] }
quote = "1.0.0"
proc_macro2_helper = "0.2.10"