FROM python:3.10-slim

RUN apt update && apt upgrade --yes && apt install libssl-dev build-essential curl pkg-config -y
WORKDIR /cli_build_folder
COPY . .

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/cargo install --path .
