name: Messari Substreams Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  validate-params:
    name: ValidateSubstreamsParams
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('./scripts/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: cd scripts && npm ci --ignore-scripts

      - name: Validate Substreams Params Schema
        run: cd scripts && npm run validate:params

      - name: Validate Subgraph Deployments
        run: cd scripts && npm run validate:subgraphs

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: streamingfast/substreams
          tag: v1.0.1
          cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install buf
        uses: bufbuild/buf-setup-action@v1.7.0
      - name: install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
      - name: run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: used cached Rust build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install-cli
        run: make install-cli
      - name: build all
        run: |
          chmod a+x /opt/hostedtoolcache/streamingfast/substreams/v1.0.1/linux-x64/substreams
          export PATH="/opt/hostedtoolcache/streamingfast/substreams/v1.0.1/linux-x64/:$PATH"
          make build-all
