name: Release
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: streamingfast/substreams
          tag: v1.0.1
          cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install buf
        uses: bufbuild/buf-setup-action@v1.7.0
      - name: install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
      - name: run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: used cached Rust build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: build all
        run: |
          chmod a+x /opt/hostedtoolcache/streamingfast/substreams/v1.0.1/linux-x64/substreams
          export PATH="/opt/hostedtoolcache/streamingfast/substreams/v1.0.1/linux-x64/:$PATH"
          make build-all

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('./scripts/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: cd scripts && npm ci --ignore-scripts

      - name: Auth AWS
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Upload updated SPKGs and Config
        run: |
          MERGE_FILES=$(git diff --name-only HEAD^ HEAD)

          cd scripts
          mkdir /tmp/spkgs

          IFS=$'\n'
          for substream in $(npm run versions:update:list $(echo $MERGE_FILES) -s | jq --raw-output '.[] ')
          do
            FILE=$(echo "../$substream/substreams.yaml")
            substreams pack $FILE --output-file /tmp/spkgs/$(echo $substream).spkg
          done
          unset IFS

          npm run spkgs:upload ${{ secrets.S3_REGION }} ${{ secrets.S3_BUCKET }}
