[package]
name = "rand_derive2"
version = "0.1.18"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc_macro2_helper = "0.2"